name: SpeedUHCWorldGen
version: 1.3
main: pl.grok.speeduhc.SpeedUHCWorldGen
api-version: 1.21
author: Grok
description: Bezpieczny generator map Speed UHC

commands:
  createuhc:
    description: Tworzy 4 customowe mapy Speed UHC
    usage: /createuhc <nazwa_bazowa>
    permission: speeduhc.create
